---
# Auth 서비스를 위한 HPA 설정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: vss
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service  # 대상 디플로이먼트 이름
  minReplicas: 3        # 최소 파드 수
  maxReplicas: 5        # 최대 파드 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # CPU 사용률 80%를 초과하면 스케일 아웃
---
# Exchange 서비스를 위한 HPA 설정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: exchange-service-hpa
  namespace: vss
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exchange-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
# Portfolio 서비스를 위한 HPA 설정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-service-hpa
  namespace: vss
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
# Stock-KR 서비스를 위한 HPA 설정
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stock-kr-service-hpa
  namespace: vss
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-kr-service
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

# 주의사항:
# 각 서비스의 리소스 요청(requests)이 적절히 설정되어 있어야 HPA가 정확히 작동
# 초기 적용 후 모니터링을 통해 각 서비스의 특성에 맞게 설정을 조정
# 급격한 트래픽 변동에 대비해 버퍼를 두는 것이 좋음 (예: maxReplicas를 예상 최대치보다 약간 높게 설정).