apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
  namespace: vss
  labels:
    app.kubernetes.io/name: exchange-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: exchange-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exchange-service
    spec:
      serviceAccountName: secrets-sa
      containers:
      - name: exchange-service
        image: 707677861059.dkr.ecr.ap-northeast-2.amazonaws.com/exchange_service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8004
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        env:
          - name: FLASK_APP
            value: "app.app:create_app"
          - name: DATABASE_URL
            value: "mysql+pymysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)"
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8004
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 8004
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: exchange-service
  namespace: vss
  labels:
    app.kubernetes.io/name: exchange-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: exchange-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
