apiVersion: v1
kind: Secret
metadata:
  name: stock-key-secret
  namespace: vss
type: Opaque
data:
  koreainvestment.key: "UFNTcExxWEhzbjNjV3RXWFp4UXhBZjhNWXNMSVRqQzFoTzcxCldPUnh3S0trL0gwYnVrOVdTSVJVajRDNkxlOVJTalBTMUtuR3F6VnQ2TGVvTHcwOUNPS0l1cURqTjQ4eDI4UTF6YkZZeTl1VXo1bkUwK3M4TTh2b0JrRzJwYjdIYVg1QUZjSUFIZTB5QThwZDZiNllEUGcySXRpTVlQdjlEbEc1R0IvKzNVV2p4akY0SWkyLzV0ZHNKZTBDSEZFb1JsaW1uR0F2UDdmdEViQUZ2bHA1NnpNPQo2NzYwODgwMC0wMQ=="