# external-secret-karpenter.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: karpenter-credentials
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: karpenter-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: karpenter/credentials
        property: access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: karpenter/credentials
        property: secret_key