apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: orders-topic
  namespace: infra
  labels:
    strimzi.io/cluster: kafka # 클러스터 이름과 일치해야 함
spec:
  partitions: 1 # 개발 환경에서는 적은 파티션 수로 시작 가능
  replicas: 1   # 개발 환경에서는 복제본을 최소화 (프로덕션에서는 더 높게 설정)