---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-metrics
  namespace: infra
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
        name: "kafka_server_$1_$2"
      - pattern: "kafka.network<type=(.+), name=(.+)><>Value"
        name: "kafka_network_$1_$2"
---
# KafkaNodePool 리소스 정의
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: k-nodes
  namespace: infra
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        class: kafka-ebs-sc
---
# Kafka 클러스터 리소스 정의
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: infra
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.9.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      log.level: "INFO"
      log4j.logger.org.apache.kafka: "INFO"
      log4j.logger.kafka: "INFO"
      log4j.logger.state.change.logger: "TRACE"
      log4j.logger.kafka.request.logger: "WARN"
      log.retention.hours: 168
      log.retention.bytes: 1073741824
      log.segment.bytes: 1073741824
      log.cleanup.policy: delete
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
