apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: vss
data:
  MYSQL_HOST: "rds.tf.private.com"
  MYSQL_PORT: "3306"
  FLASK_ENV: "development"
  PYTHONPATH: "/app"
  AUTH_SCHEMA: "auth_db"
  PORTFOLIO_SCHEMA: "portfolio_db"
  EXCHANGE_SCHEMA: "exchange_db"
  REDIS_HOST: "redis.infra.svc.cluster.local"
  REDIS_PORT: "6379"
  SECRET_KEY: "vss_secret_key"
  KAKAO_SECRET_KEY: "d37e3286aa4a1b7e3a2c084309f70d72"
  CACHE_DURATION: "300"
  KAFKA_BROKER_HOST: "kafka-kafka-bootstrap.infra.svc.cluster.local:9092"
  BASE_URL: "https://www.stockstalk.store"
  AUTH_SERVICE_URL: "https://www.stockstalk.store/auth"
  EXCHANGE_SERVICE_URL: "https://www.stockstalk.store/exchange"
  PORTFOLIO_SERVICE_URL: "https://www.stockstalk.store/portfolio"