# external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: vss
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: 'rds!db-0e75a494-02ae-4548-a114-d9aed61164ea'
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: 'rds!db-0e75a494-02ae-4548-a114-d9aed61164ea'
        property: password