apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-ebs-sc
provisioner: ebs.csi.aws.com             # EBS CSI 드라이버 사용 -> 동적으로 EBS 볼륨 프로비저닝
volumeBindingMode: WaitForFirstConsumer  # Pod가 할당될 때까지 대기
allowVolumeExpansion: true               # 필요 시 볼륨 크기 확장 가능
parameters:
  type: gp3                              # EBS 볼륨 타입 (gp2, gp3 가능)
  fsType: ext4        # 볼륨 파일 시스템 타입